
dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  # เปลี่ยนไอคอนเเอพ
  flutter_launcher_icons: "^0.14.4"
  # api เชื่อมต่อเเอพกับฐานข้อมูล
  http: ^1.6.0  
  # เเพคเก็จตกเเต่งเนกิเวชั่นบาร์
  curved_navigation_bar: ^1.0.6 #latest version
  # เเพจเก็จช่วยตรวจจับข้อมูลที่กรอก กำหนดรูปเเบบ 
  form_field_validator: ^1.1.0
  # เเพเก็จ ส่งรูป api
  image_picker: ^1.2.1
  # เเก้ api cache 
  flutter_cache_manager: ^3.4.1
  # รูป

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/itemlogo.png"

  web:
    generate: true
    image_path: "assets/itemlogo.png"
    background_color: "#ffffff"
    theme_color: "#1E293B"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/
  #   - assets/item.jpeg
